// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

[id="proc-pushing-your-changes-to-remote-git-repository_{context}"]
= Pushing your changes to remote Git repository

[role="_abstract"]
When you have saved your changes locally, push the changes to your remote Git repository. 


.Prerequisites
* The local Git repository is added to Eclipse IDE.

.Procedure
. Stage your changes.
.. In the *Git Staging* view, select the files listed in the *Unstaged Changes* pane that you want to stage. 
.. Click the the plus icon to stage the selceted files.  
+
The selected files are now listed in the *Staged Changes* pane.

. Commit and push your changes.
+
NOTE: If you want to amend a previous commit, click the icon for *Amend* that is located in the *Commit Message* pane.
 
.. In the *Git Staging* view, enter the commit message in the *Commit Message* pane.
.. Click *Commit and Push*.
.. In the *Push branch in Remote* dialog, review the following options:
+
* Unselect *Configure upstream for push and pull*.
* If you have amended a commit that was already pushed previously, select *Force overwrite branch in remote if it exists and has diverged.*. 

.. Click *Next*.
.. Click *Finish*.

.Verification steps


[role="_additional-resources"]
.Additional resources