[id="updating-local-development-branch-by-resetting-it_{context}"]
= Resetting the local main branch with the remote main branch

Reset your local main branch with the remote main branch to make your local main branch up-to-date with the remote main branch.

In this procedure, we assume that main, or the default, branch is called `main`. 

[NOTE]
====
This procedure is not suitable for all workflows. If you are not sure whether your workflow requires a reset, consult the contribution guide for your project.  
====

.Prerequisites
* You have fetched the latest changes from remote repository.

.Procedure

. In the *Git Repositories* view, expand your working repository.
. Expand *Branches* -> *Local*.
. See which branch you are in - the branch has a check-mark.
+
If you are in a branch other than the development branch, commit all the changes from the *Git Staging* view.
+
[IMPORTANT]
====
Eclipse IDE does not warn you if you have uncommitted changes when checking out another branch. 
====
. Double-click `main` to checkout the `main` branch.

. Expand *Remote Tracking*.
. Right-click the name of the branch you are resetting to.
+
For example, if your remote repository is called `upstream`, right-click `upstream/main`.

. Click *Reset*, select *Hard*.
+
[WARNING]
====
A hard reset causes you to lose all the local changes in your current branch.  
====
. Click *Finish*.  

Your local main branch is up-to-date with the remote main branch.